package model.database.POJO;
// Generated Mar 28, 2018 5:38:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private Integer countryId;
     private String countryName;
     private Date modifiedDate;
     private Set<CityOrDistrict> cityOrDistricts = new HashSet<CityOrDistrict>(0);

    public Country() {
    }

	
    public Country(String countryName, Date modifiedDate) {
        this.countryName = countryName;
        this.modifiedDate = modifiedDate;
    }
    public Country(String countryName, Date modifiedDate, Set<CityOrDistrict> cityOrDistricts) {
       this.countryName = countryName;
       this.modifiedDate = modifiedDate;
       this.cityOrDistricts = cityOrDistricts;
    }
   
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set<CityOrDistrict> getCityOrDistricts() {
        return this.cityOrDistricts;
    }
    
    public void setCityOrDistricts(Set<CityOrDistrict> cityOrDistricts) {
        this.cityOrDistricts = cityOrDistricts;
    }




}


