package model.database.POJO;
// Generated Mar 28, 2018 5:38:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer invoiceId;
     private SpecialPromotion specialPromotion;
     private Users users;
     private Date invoiceDueDate;
     private float totalPrice;
     private String description;
     private Date modifiedDate;
     private String invoiceStatus;
     private Set<UserTripLog> userTripLogs = new HashSet<UserTripLog>(0);
     private Set<InvoiceLineItem> invoiceLineItems = new HashSet<InvoiceLineItem>(0);

    public Invoice() {
    }

	
    public Invoice(Users users, Date invoiceDueDate, float totalPrice, Date modifiedDate, String invoiceStatus) {
        this.users = users;
        this.invoiceDueDate = invoiceDueDate;
        this.totalPrice = totalPrice;
        this.modifiedDate = modifiedDate;
        this.invoiceStatus = invoiceStatus;
    }
    public Invoice(SpecialPromotion specialPromotion, Users users, Date invoiceDueDate, float totalPrice, String description, Date modifiedDate, String invoiceStatus, Set<UserTripLog> userTripLogs, Set<InvoiceLineItem> invoiceLineItems) {
       this.specialPromotion = specialPromotion;
       this.users = users;
       this.invoiceDueDate = invoiceDueDate;
       this.totalPrice = totalPrice;
       this.description = description;
       this.modifiedDate = modifiedDate;
       this.invoiceStatus = invoiceStatus;
       this.userTripLogs = userTripLogs;
       this.invoiceLineItems = invoiceLineItems;
    }
   
    public Integer getInvoiceId() {
        return this.invoiceId;
    }
    
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }
    public SpecialPromotion getSpecialPromotion() {
        return this.specialPromotion;
    }
    
    public void setSpecialPromotion(SpecialPromotion specialPromotion) {
        this.specialPromotion = specialPromotion;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getInvoiceDueDate() {
        return this.invoiceDueDate;
    }
    
    public void setInvoiceDueDate(Date invoiceDueDate) {
        this.invoiceDueDate = invoiceDueDate;
    }
    public float getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(float totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getInvoiceStatus() {
        return this.invoiceStatus;
    }
    
    public void setInvoiceStatus(String invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }
    public Set<UserTripLog> getUserTripLogs() {
        return this.userTripLogs;
    }
    
    public void setUserTripLogs(Set<UserTripLog> userTripLogs) {
        this.userTripLogs = userTripLogs;
    }
    public Set<InvoiceLineItem> getInvoiceLineItems() {
        return this.invoiceLineItems;
    }
    
    public void setInvoiceLineItems(Set<InvoiceLineItem> invoiceLineItems) {
        this.invoiceLineItems = invoiceLineItems;
    }




}


