package model.database.POJO;
// Generated Apr 9, 2018 1:47:50 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Seat generated by hbm2java
 */
public class Seat  implements java.io.Serializable {


     private Byte seatId;
     private Coach coach;
     private byte seatStatus;
     private String seatDescription;
     private Date modifiedDate;

    public Seat() {
    }

	
    public Seat(Coach coach, byte seatStatus, Date modifiedDate) {
        this.coach = coach;
        this.seatStatus = seatStatus;
        this.modifiedDate = modifiedDate;
    }
    public Seat(Coach coach, byte seatStatus, String seatDescription, Date modifiedDate) {
       this.coach = coach;
       this.seatStatus = seatStatus;
       this.seatDescription = seatDescription;
       this.modifiedDate = modifiedDate;
    }
   
    public Byte getSeatId() {
        return this.seatId;
    }
    
    public void setSeatId(Byte seatId) {
        this.seatId = seatId;
    }
    public Coach getCoach() {
        return this.coach;
    }
    
    public void setCoach(Coach coach) {
        this.coach = coach;
    }
    public byte getSeatStatus() {
        return this.seatStatus;
    }
    
    public void setSeatStatus(byte seatStatus) {
        this.seatStatus = seatStatus;
    }
    public String getSeatDescription() {
        return this.seatDescription;
    }
    
    public void setSeatDescription(String seatDescription) {
        this.seatDescription = seatDescription;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


