package model.database.POJO;
// Generated Mar 28, 2018 5:38:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserGoogleAccount generated by hbm2java
 */
public class UserGoogleAccount  implements java.io.Serializable {


     private int userId;
     private Users users;
     private byte[] googleId;
     private Date modifiedDate;

    public UserGoogleAccount() {
    }

    public UserGoogleAccount(Users users, byte[] googleId, Date modifiedDate) {
       this.users = users;
       this.googleId = googleId;
       this.modifiedDate = modifiedDate;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public byte[] getGoogleId() {
        return this.googleId;
    }
    
    public void setGoogleId(byte[] googleId) {
        this.googleId = googleId;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


