package model.database.POJO;
// Generated Mar 28, 2018 5:38:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private Role role;
     private byte isGoogleLogin;
     private byte isFacebookLogin;
     private Date modifiedDate;
     private UserFacebookAccount userFacebookAccount;
     private UserInfo userInfo;
     private Set<UserTripLog> userTripLogs = new HashSet<UserTripLog>(0);
     private UserPaymentInfo userPaymentInfo;
     private LoginInfo loginInfo;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);
     private Set<SpecialPromotion> specialPromotions = new HashSet<SpecialPromotion>(0);
     private UserGoogleAccount userGoogleAccount;

    public Users() {
    }

	
    public Users(Role role, byte isGoogleLogin, byte isFacebookLogin, Date modifiedDate) {
        this.role = role;
        this.isGoogleLogin = isGoogleLogin;
        this.isFacebookLogin = isFacebookLogin;
        this.modifiedDate = modifiedDate;
    }
    public Users(Role role, byte isGoogleLogin, byte isFacebookLogin, Date modifiedDate, UserFacebookAccount userFacebookAccount, UserInfo userInfo, Set<UserTripLog> userTripLogs, UserPaymentInfo userPaymentInfo, LoginInfo loginInfo, Set<Invoice> invoices, Set<SpecialPromotion> specialPromotions, UserGoogleAccount userGoogleAccount) {
       this.role = role;
       this.isGoogleLogin = isGoogleLogin;
       this.isFacebookLogin = isFacebookLogin;
       this.modifiedDate = modifiedDate;
       this.userFacebookAccount = userFacebookAccount;
       this.userInfo = userInfo;
       this.userTripLogs = userTripLogs;
       this.userPaymentInfo = userPaymentInfo;
       this.loginInfo = loginInfo;
       this.invoices = invoices;
       this.specialPromotions = specialPromotions;
       this.userGoogleAccount = userGoogleAccount;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public byte getIsGoogleLogin() {
        return this.isGoogleLogin;
    }
    
    public void setIsGoogleLogin(byte isGoogleLogin) {
        this.isGoogleLogin = isGoogleLogin;
    }
    public byte getIsFacebookLogin() {
        return this.isFacebookLogin;
    }
    
    public void setIsFacebookLogin(byte isFacebookLogin) {
        this.isFacebookLogin = isFacebookLogin;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public UserFacebookAccount getUserFacebookAccount() {
        return this.userFacebookAccount;
    }
    
    public void setUserFacebookAccount(UserFacebookAccount userFacebookAccount) {
        this.userFacebookAccount = userFacebookAccount;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public Set<UserTripLog> getUserTripLogs() {
        return this.userTripLogs;
    }
    
    public void setUserTripLogs(Set<UserTripLog> userTripLogs) {
        this.userTripLogs = userTripLogs;
    }
    public UserPaymentInfo getUserPaymentInfo() {
        return this.userPaymentInfo;
    }
    
    public void setUserPaymentInfo(UserPaymentInfo userPaymentInfo) {
        this.userPaymentInfo = userPaymentInfo;
    }
    public LoginInfo getLoginInfo() {
        return this.loginInfo;
    }
    
    public void setLoginInfo(LoginInfo loginInfo) {
        this.loginInfo = loginInfo;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }
    public Set<SpecialPromotion> getSpecialPromotions() {
        return this.specialPromotions;
    }
    
    public void setSpecialPromotions(Set<SpecialPromotion> specialPromotions) {
        this.specialPromotions = specialPromotions;
    }
    public UserGoogleAccount getUserGoogleAccount() {
        return this.userGoogleAccount;
    }
    
    public void setUserGoogleAccount(UserGoogleAccount userGoogleAccount) {
        this.userGoogleAccount = userGoogleAccount;
    }




}


